language: cpp
branches:
  only:
  - master

matrix:
  include:
  - name
    sudo: required
    before_install:
      - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz -O premake.tar.gz
      - tar -xf premake.tar.gz
    env:
      - PREMAKE=1

      
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then eval "${MATRIX_EVAL}"; fi
  - if [ "${PREMAKE}" = "1" ]; then cd RecastDemo && ../premake5 gmake && cd ..; fi
  - if [ "${PREMAKE}" != "1" ]; then mkdir -p build && cd build && ${ANALYZE} cmake ../ && cd ..; fi

script:  # 2 CPUs on Travis-CI + 1 extra for IO bound process
  - if [ "${PREMAKE}" = "1" ]; then make -C RecastDemo/Build/gmake -j3; fi
  - if [ "${PREMAKE}" != "1" ]; then make -C build -j3; fi
  - if [ "${PREMAKE}" = "1" ]; then RecastDemo/Bin/Tests; fi
  - if [ "${PREMAKE}" != "1" ]; then cd build && ctest; fi